development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      uri: mongodb://teamKetchupBot:Today123!@kahana.mongohq.com:10027/emotional_securities_dev
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
test:
  sessions:
    default:
      database: emo_securities_test
      hosts:
        - localhost:27017
      options:
      # raise_not_found_error: false
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
