sample_tweet = { :created_at=>"Thu Jul 24 21:51:40 +0000 2014", 
	:id=>492426915811430400, 
	:id_str=>"492426915811430400", 
	:text=>"Apple reports end of iPad, next day $AAPL's up 2.2%. \n\nAmazon reports another earnings miss, $AMZN's down 10% in after-hours. \n\nApocalypse?", 
	:source=>"<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>", :truncated=>false, :in_reply_to_status_id=>nil, 
	:in_reply_to_status_id_str=>nil, 
	:in_reply_to_user_id=>nil, 
	:in_reply_to_user_id_str=>nil, 
	:in_reply_to_screen_name=>nil, 
	:user=>
		{ :id=>19225408, 
			:id_str=>"19225408", 
			:name=>"Kontra", 
			:screen_name=>"counternotions", 
			:location=>"NYC", 
			:url=>"http://counternotions.com", 
			:description=>"Trying is the first step to failure. Veteran design and management surgeon, perennially in search of complex problems to operate on.", 
			:protected=>false, 
			:verified=>false, 
			:followers_count=>63115, 
			:friends_count=>94, 
			:listed_count=>1216, 
			:favourites_count=>180, 
			:statuses_count=>55209, 
			:created_at=>"Tue Jan 20 08:47:08 +0000 2009", 
			:utc_offset=>-14400, 
			:time_zone=>"Eastern Time (US & Canada)", 
			:geo_enabled=>false, :lang=>"en", 
			:contributors_enabled=>false, 
			:is_translator=>false, 
			:profile_background_color=>"383838", 
			:profile_background_image_url=>"http://pbs.twimg.com/profile_background_images/7091668/darkwood-bkg.jpg", 
			:profile_background_image_url_https=>"https://pbs.twimg.com/profile_background_images/7091668/darkwood-bkg.jpg", 
			:profile_background_tile=>true, 
			:profile_link_color=>"B55930", 
			:profile_sidebar_border_color=>"FFFFFF", 
			:profile_sidebar_fill_color=>"FCEBD5", 
			:profile_text_color=>"333333", 
			:profile_use_background_image=>true, 
			:profile_image_url=>"http://pbs.twimg.com/profile_images/472995716663488512/0MErVHN__normal.png", 
			:profile_image_url_https=>"https://pbs.twimg.com/profile_images/472995716663488512/0MErVHN__normal.png", 
			:profile_banner_url=>"https://pbs.twimg.com/profile_banners/19225408/1401605752", 
			:default_profile=>false, 
			:default_profile_image=>false, 
			:following=>nil, 
			:follow_request_sent=>nil, 
			:notifications=>nil }, 

			:geo=>nil, 
			:coordinates=>nil, 
			:place=>nil, 
			:contributors=>nil, 
			:retweet_count=>0, 
			:favorite_count=>0, 
			:entities=> 
				{ :hashtags=>[], 
					:trends=>[], 
					:urls=>[], 
					:user_mentions=>[], 
					:symbols=>[
						{:text=>"AAPL", 
							:indices=>[36, 41]}, 
						{:text=>"AMZN", :indices=>[93, 98]}]}, 
						:favorited=>false, 
						:retweeted=>false, 
						:possibly_sensitive=>false, 
						:filter_level=>"medium", 
						:lang=>"en" }

###################################################


